sbt_version = 1.12.6
scalaVersion = 3.3.7
organization = com.your-domain
organizationName =
author_name = Your Name
author_email = some@email
github_username = 
repo_name = repo-name
project_name = $repo_name$
cats_version = 2.13.0
cats_effect_version = 3.7.0
refined4s_version = 1.16.0
hedgehog_version = 0.13.0
