sbt_version = 1.13.0
scalaVersion = 3.3.8
organization = com.your-domain
organizationName =
author_name = Your Name
author_email = some@email
github_username = 
repo_name = repo-name
project_name = $repo_name$
cats_version = 2.13.0
cats_effect_version = 3.7.1
kittens_version = 3.5.0
refined4s_version = 1.21.0
hedgehog_version = 0.15.0
